**Numpy**

1.   pip install numpy #for jupyter notebook and Idle
2.   Numpy - Numerical python
3.   Numpy - Jim Hugunin
4.  **Note**

    list - similar or mixed datatypes
  
    array - similar only

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

**Chapter 1 - Attributes**

1. Shape

In [ ]:
a.shape

(2, 3)

2. Size

In [ ]:
a.size

6

3. Reshape

In [ ]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

4. Transpose

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

5. ndim

In [ ]:
a.ndim

2

**Functions**

1. Creation of array

In [ ]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

2. Reshape

In [ ]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

3. Concatenate

In [ ]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

4. Horizontally

In [ ]:
np.concatenate((a,b),1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

5. Vertically

In [ ]:
np.concatenate((a,b),0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Chapter 2 - Numpy - Array Creation Routine**

1. np.empty

In [ ]:
np.empty((2,3))

array([[4.52671581e-316, 0.00000000e+000, 2.79147090e-321],
       [4.94201138e-316, 4.69723387e-316, 6.59706251e-310]])

In [ ]:
np.empty((2,3), dtype=int)

array([[       91621748,               0,             565],
       [      100027424,        95073072, 133526031711472]])

2. np.zeros

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

3. np.ones

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

4. np.eye

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

5. np.arange(start, stop, step, dtype)

In [ ]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(1,7, step=2) #step skips n-1 number

array([1, 3, 5])

6. np.linspace(start, end, divide)

In [ ]:
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

Indexing and Slicing

In [ ]:
#indexing
arr1 = np.arange(1,11)
arr2 = arr1[[1,4]]
arr1
arr2

array([2, 5])

In [ ]:
#slicing
arr1 = np.arange(1,11)
arr2 = arr1[1:4]
arr2

array([2, 3, 4])

**Chapter 3 - Numpy - Array Selection**

In [ ]:
x = np.arange(1,11)
a = list(range(1,11))

multiplications

In [ ]:
x*4  #array multiplies n with elements

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [ ]:
a*4  #list repeats itself n times

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

**Masking/Filtering/Selection**

In [ ]:
#example1
x>5   #condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
mask = x>5         #masking
x[mask]

array([ 6,  7,  8,  9, 10])

In [ ]:
#or
x[x>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
#example2
names = np.array(['Pratik', 'Faizan', 'Alok', 'Pratik', 'Ayush', 'Pratik', 'Faizan'])

In [ ]:
names == 'Pratik'    #condition
mask = names == 'Pratik' #masking
names[mask]

array(['Pratik', 'Pratik', 'Pratik'], dtype='<U6')

In [ ]:
#or
names[names == 'Pratik']

array(['Pratik', 'Pratik', 'Pratik'], dtype='<U6')

In [ ]:
#select all values which is not 'Pratik'
names[names != 'Pratik']

array(['Faizan', 'Alok', 'Ayush', 'Faizan'], dtype='<U6')

OR -> |

In [ ]:
(names == 'Pratik') | (names == 'Faizan')   #condition

array([ True,  True, False,  True, False,  True,  True])

In [ ]:
names[(names == 'Pratik') | (names == 'Faizan')]  #masking

array(['Pratik', 'Faizan', 'Pratik', 'Pratik', 'Faizan'], dtype='<U6')

In [ ]:
#select all the values, which is not pratik and change them to purvesh
names[names != 'Pratik'] == 'Purvesh'

array([False, False, False, False])

In [ ]:
names

array(['Pratik', 'Faizan', 'Alok', 'Pratik', 'Ayush', 'Pratik', 'Faizan'],
      dtype='<U6')

In [ ]:
np.unique(names)

array(['Alok', 'Ayush', 'Faizan', 'Pratik'], dtype='<U6')

**Chapter 4 - Trignometric Functions**

In [ ]:
print(f"Sin -> {np.sin(90)}")
print(f"Cos -> {np.cos(90)}")
print(f"Tan -> {np.tan(90)}")
print(f"log -> {np.log(10)}")
print(f"log -> {np.log(1)}")
print(f"log10 -> {np.log10(10)}")
print(f"log of log10 -> {np.log(np.log10(5))}")

Sin -> 0.8939966636005579
Cos -> -0.4480736161291701
Tan -> -1.995200412208242
log -> 2.302585092994046
log -> 0.0
log10 -> 1.0
log of log10 -> -0.35814744992084513


In [ ]:
np.sqrt(25)

np.float64(5.0)

In [ ]:
a = np.array([[1,4,6],[3,5,7],[0,2,-6]])
b = np.array([[2,6,1],[6,4,2],[6,8,9]])

In [ ]:
a

array([[ 1,  4,  6],
       [ 3,  5,  7],
       [ 0,  2, -6]])

In [ ]:
b

array([[2, 6, 1],
       [6, 4, 2],
       [6, 8, 9]])

In [ ]:
np.add(a,b)

array([[ 3, 10,  7],
       [ 9,  9,  9],
       [ 6, 10,  3]])

In [ ]:
np.subtract(a,b)

array([[ -1,  -2,   5],
       [ -3,   1,   5],
       [ -6,  -6, -15]])

In [ ]:
np.multiply(a,b)

array([[  2,  24,   6],
       [ 18,  20,  14],
       [  0,  16, -54]])

In [ ]:
np.divide(a,b)

array([[ 0.5       ,  0.66666667,  6.        ],
       [ 0.5       ,  1.25      ,  3.5       ],
       [ 0.        ,  0.25      , -0.66666667]])

In [ ]:
np.remainder(a,b)

array([[1, 4, 0],
       [3, 1, 1],
       [0, 2, 3]])

In [ ]:
np.matmul(a,b)

array([[ 62,  70,  63],
       [ 78,  94,  76],
       [-24, -40, -50]])

In [ ]:
c = np.array([[1,2],[3,4]])
np.multiply(a,c)

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [ ]:
#The dot product is the standard matrix multiplication you likely learned in linear algebra. It involves a "row-by-column" summation.
#Logic: For 2D matrices, the element at position $(i, j)$ in the output is the sum of the products of the $i$-th row of $a$ and the $j$-th column of $b$.
np.dot(a,b)     #dot product of a and b

array([[ 62,  70,  63],
       [ 78,  94,  76],
       [-24, -40, -50]])

In [ ]:
#While np.dot is optimized for 1D and 2D arrays (vectors and matrices), tensordot is the "heavy-duty" version designed to handle multidimensional arrays (tensors) by summing products along specific axes.
np.tensordot(a,b)

array(46)

In [ ]:
#The Kronecker product (often denoted by the symbol ) is an operation that results in a block matrix. It is much more expansive than a dot product.
#Logic: Every single element in array $a$ is multiplied by the entire array $b$.
np.kron(a,b)

array([[  2,   6,   1,   8,  24,   4,  12,  36,   6],
       [  6,   4,   2,  24,  16,   8,  36,  24,  12],
       [  6,   8,   9,  24,  32,  36,  36,  48,  54],
       [  6,  18,   3,  10,  30,   5,  14,  42,   7],
       [ 18,  12,   6,  30,  20,  10,  42,  28,  14],
       [ 18,  24,  27,  30,  40,  45,  42,  56,  63],
       [  0,   0,   0,   4,  12,   2, -12, -36,  -6],
       [  0,   0,   0,  12,   8,   4, -36, -24, -12],
       [  0,   0,   0,  12,  16,  18, -36, -48, -54]])

**Chapter 5 - Numpy - Statistical Operation**

In [ ]:
a = np.arange(1,6)
b = np.sqrt(a)
b

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
#In NumPy, np.ceil(b) stands for the ceiling of the array elements. It is a mathematical operation that rounds each number up to the nearest integer.
#Positive numbers: It moves toward the next higher integer (e.g., 1.2 becomes 2.0).
#Negative numbers: It moves toward zero (e.g., -1.8 becomes -1.0), because $-1$ is mathematically "greater" than $-1.8$.
#Integers: If the number is already an integer (e.g., 3.0), it remains unchanged
np.ceil(b)

array([1., 2., 2., 2., 3.])

In [ ]:
x = np.random.randn(4,2)
x

array([[ 1.56306109, -1.5233578 ],
       [ 0.40795862, -0.05125258],
       [-1.22505695, -1.19814852],
       [-0.3295532 , -0.45871687]])

In [ ]:
#mean of x
x.mean()

np.float64(-0.351883275635969)

In [ ]:
#standard deviation of x
x.std()

np.float64(0.9485259752210657)

In [ ]:
#max of x
x.max()

np.float64(1.5630610917145598)

In [ ]:
#min of x
x.min()

np.float64(-1.5233578012152151)

In [ ]:
#returns the max value location
x.argmax()

np.int64(0)

In [ ]:
#returns the min value location
x.argmin()

np.int64(1)

In [ ]:
#sum of x
x.sum()

np.float64(-2.815066205087752)

In [ ]:
x.sum(axis = 1)  #for row

array([ 0.03970329,  0.35670604, -2.42320547, -0.78827007])

In [ ]:
x.sum(axis = 0)  #for coloumn

array([ 0.41640957, -3.23147577])

In [ ]:
#transpose
x.T

array([[ 1.56306109,  0.40795862, -1.22505695, -0.3295532 ],
       [-1.5233578 , -0.05125258, -1.19814852, -0.45871687]])

In [ ]:
#2D array to 1D array
x.flatten()

array([ 1.56306109, -1.5233578 ,  0.40795862, -0.05125258, -1.22505695,
       -1.19814852, -0.3295532 , -0.45871687])

Eculedian Distance Formula between two vectors
$$d = \sqrt{\sum_{i=1}^{n} (v1_i - v2_i)^2}$$

In [ ]:
v1 = np.random.randn(10)
v2 = np.random.randn(10)

In [ ]:
v1

array([-2.20351424, -0.75040576, -1.82939526, -0.27161941,  0.70350773,
        1.30136825,  0.94314882,  0.49532493, -0.84555686, -0.0041269 ])

In [ ]:
v2

array([ 0.54853719,  0.62894364, -0.97645447, -0.76974688,  2.26620016,
       -0.27155571, -1.63440916,  1.25508391,  0.44011996, -0.35608899])

In [ ]:
dist = np.sqrt(np.sum((v1-v2)**2))

In [ ]:
dist

np.float64(4.936193803785782)